INSERT INTO `countries` ( `country_name`, `country_code`,  `phone_code`) VALUES
                                                                             ('Angola', 'AO', ''),
                                                                             ('Burkina Faso', 'BF', ''),
                                                                             ('Burundi', 'BI', ''),
                                                                             ('Benin', 'BJ', ''),
                                                                             ('Botswana', 'BW', ''),
                                                                             ('Congo (Kinshasa)', 'CD', ''),
                                                                             ('Central African Republic', 'CF', ''),
                                                                             ('Congo (Brazzaville)', 'CG', ''),
                                                                             ('Ivory Coast', 'CI', ''),
                                                                             ('Cameroon', 'CM', ''),
                                                                             ('Cabo Verde', 'CV', ''),
                                                                             ('Djibouti', 'DJ', ''),
                                                                             ('Algeria', 'DZ', ''),
                                                                             ('Egypt', 'EG', ''),
                                                                             ('Western Sahara', 'EH', ''),
                                                                             ('Eritrea', 'ER', ''),
                                                                             ('Ethiopia', 'ET', ''),
                                                                             ('Gabon', 'GA', ''),
                                                                             ('Ghana', 'GH', ''),
                                                                             ('Gambia, The', 'GM', ''),
                                                                             ('Guinea', 'GN', ''),
                                                                             ('Equatorial Guinea', 'GQ', ''),
                                                                             ('Guinea-Bissau', 'GW', ''),
                                                                             ( 'Kenya', 'KE', ''),
                                                                             ( 'Comoros', 'KM', ''),
                                                                             ( 'Liberia', 'LR', ''),
                                                                             ( 'Lesotho', 'LS', ''),
                                                                             ( 'Libya', 'LY', ''),
                                                                             ( 'Morocco', 'MA', ''),
                                                                             ( 'Madagascar', 'MG', ''),
                                                                             ( 'Mali', 'ML', ''),
                                                                             ( 'Mauritania', 'MR', ''),
                                                                             ( 'Mauritius', 'MU', ''),
                                                                             ( 'Malawi', 'MW', ''),
                                                                             ( 'Mozambique', 'MZ', ''),
                                                                             ( 'Namibia', 'NA', ''),
                                                                             ( 'Niger', 'NE', ''),
                                                                             ( 'Nigeria', 'NG', ''),
                                                                             ( 'Reunion', 'RE', ''),
                                                                             ( 'Rwanda', 'RW', ''),
                                                                             ( 'Seychelles', 'SC', ''),
                                                                             ( 'Sudan', 'SD', ''),
                                                                             ( 'Sierra Leone', 'SL', ''),
                                                                             ( 'Senegal', 'SN', ''),
                                                                             ( 'Somalia', 'SO', ''),
                                                                             ( 'South Sudan', 'SS', ''),
                                                                             ( 'Sao Tome And Principe', 'ST', ''),
                                                                             ( 'Chad', 'TD', ''),
                                                                             ( 'Togo', 'TG', ''),
                                                                             ( 'Tunisia', 'TN', ''),
                                                                             ( 'Tanzania', 'TZ', ''),
                                                                             ( 'Uganda', 'UG', ''),
                                                                             ( 'Mayotte', 'YT', ''),
                                                                             ( 'South Africa', 'ZA', ''),
                                                                             ( 'Zambia', 'ZM', ''),
                                                                             ( 'Zimbabwe', 'ZW', '');
